### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by ghost** [torservers/onionize-docker#1]
Do you plan to build an ARM compatible image of this project ? 
Using BuildX : https://developer.arm.com/common-tasks/getting-started-with-docker/multi-architecture-images

**Comment by ghost** [comment]
I created an image for `armhf` architectures using `buildx`, image here : https://hub.docker.com/repository/docker/rriclet/onionize

I forked your project, changed the architecture of `docker-gen` used in your Dockerfile.

**Comment by ghost** [comment]
A cleaner solution would be for you to add a `armhf` tag on Docker Hub (using `buildx`).

For now, I created my own image : 
https://hub.docker.com/repository/docker/rriclet/onionize/general

Here is the application and and build process using `buildx` :
https://itnext.io/nextcloud-docker-raspberry-pi-onion-service-84d4af13f7e6

**Comment by moba** [comment]
Thank you! Really appreciated. I will have a look at this soon. I am largely offline this year, sorry for the delayed response.

**Comment by moba** [comment]
I've looked at the documentation, and I believe the best way to address this is to build docker-gen in an intermediary container. This should work regardless of architecture.

To be honest I have not tested this yet. Let's see what happens when Docker Hub picks this up. And please try it out! I don't have any armhf devices at hand.

**Comment by moba** [comment]
Ah OK, Docker Hub cannot auto build for other architectures yet. ( https://github.com/docker/roadmap/issues/109 )

Guess I have to build and push manually then...

**Comment by ghost** [comment]
Yes, I built my `armhf` manually with `buildx`. Everything is explained in this article : 
https://itnext.io/nextcloud-docker-raspberry-pi-onion-service-84d4af13f7e6

Buildx documentation :
https://docs.docker.com/buildx/working-with-buildx

To push an image to DockerHub from my non-`arm` laptop, I used this command :
`docker buildx build --platform linux/arm/v7 -t rriclet/onionize:arm32v7 --push .`

**Comment by moba** [comment]
Should already be up under the "latest" tag: https://hub.docker.com/r/torservers/onionize/tags

**Comment by moba** [comment]
aaand they are gone again. looks like automated builds replace previous uploads, makes sense. will disable and rebuild/upload again.
