### ISSUE TITLE
x86/amd64 images in docker hub?

### ISSUE THREAD

**Issue by ellenhp** [torservers/onionize-docker#7]
Is it just me or are there no x86 based images in docker hub? It might be cool to add them if possible since I bet I'm not the only one working on a service that won't run on arm or ppc.

**Comment by ellenhp** [comment]
Maybe they were removed in the resolution of #1?

**Comment by moba** [comment]
Ooops. You are absolutely right. Pushed 386/amd64 now, too. Thanks!
